package com.aware.smartphoneuse;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Dictionary;
import java.util.List;
import java.util.Map;
import java.util.Vector;

class Constants {
    static final String TAG = "MATAG";
    // Different phases for intervention.
    static final Vector<String> phases = new Vector<String>(Arrays.asList("NO_INTERVENTION", "POP_UP_LAYOUT", "MEANINGFUL_TEXT", "RANDOM_TEXT", "MEANINGFUL_AUDIO"));
    static final Vector<String> phases_cn = new Vector<String>(Arrays.asList("NO_INTERVENTION", "POP_UP_LAYOUT", "MEANINGFUL_TEXT", "RANDOM_TEXT", "MEANINGFUL_AUDIO"));

    // Passwords for switching between different phases.
    static final String PhasePwd1 = "1";
    static final String PhasePwd2 = "2";
    static final String PhasePwd3 = "3";
    static final String PhasePwd4 = "4";
    static final String PhasePwd5 = "set5xh_remove"; // Phase 5 has been remove from the experimental version
    static final String ACTION_SWITCH_PHASE = "ACTION_SWITCH_PHASE";
    static final String ACTION_FIRST_RUN_APPUSEPLUGIN = "ACTION_FIRST_RUN_APPUSEPLUGIN";

    static final String ACTION_WHITELIST_CHANGED = "ACTION_WHITELIST_CHANGED";

    static final String ACTION_ENSURE_PLUGIN_WORKING = "ACTION_ENSURE_PLUGIN_WORKING";

    // Passwords for entering the setting page for different phases
    static final String WhiteListPwd1 = "1";
    static final String WhiteListPwd2 = "2";
    static final String WhiteListPwd3 = "3";
    static final String WhiteListPwd4 = "4";
    static final String WhiteListPwd5 = "blset5xh_remove";// Phase 5 has been remove from the experimental version

    // Currently give intervention at everytime since WorkSleepTimeFlag is false, if the flag is ture, then
    // intervention will be triggered according to the WorkSleepTime variable below.
    static final boolean WorkSleepTimeFlag = false;

    /*
    Time for work and sleep, format as shown below:
    WorkSleepTime = {
    Start_hour, Start_minute, End_hour, End_minute ------- Weekday Work Time
    Start_hour, Start_minute, End_hour, End_minute ------- Weekday Sleep Time
    Start_hour, Start_minute, End_hour, End_minute ------- Weekend Work Time
    Start_hour, Start_minute, End_hour, End_minute ------- Weekend Sleep Time
    Start_hour, Start_minute, End_hour, End_minute ------- Noon Break Time
    }

    In the case of WorkSleepTimeFlag is true, the intervention will be triggered if
    the day of week and the time is in the range of work time or sleep time and not in the noon break time.
    That is because we want to block user to overuse their smartphone while they are suppose to work or sleep,
    however, users can freely use their smartphone in the time of noon break.
    */
    static final int[] WorkSleepTime = {
            0,0,0,0,
            0,0,0,0,
            0,0,0,0,
            0,0,0,0,
            0,0,0,0};

    //Control whether will the intervention layer will pop up while user are using APPs in the blacklist or not.
    static final boolean[] enableUsingPopUp = {false}; //Enable use the APP using time limit and pop up overlay in Plugin.java
    static final boolean[] enableWaitingPopUp = {false};//Enable waiting for the time of limitation to come
    //Check whether user are first time open the app or not.
    static final boolean[] firstTime = {true};
    static final Map<String, Boolean> lastInputRight = new HashMap<String,Boolean>();
    static final Map<String, Long> lastInputTime = new HashMap<String,Long>();
    static final Map<String, Long> lastUsingTime = new HashMap<String,Long>();
    static final long[] lastEqualTime = {0}; // Store the timestamp of last time the next app equal to current app
    static final long[] lastSNSTime = {0}; // Store the timestamp of last time enter the Wechat SNS page
    static final long[] lastWechatEnterTime = {0}; // Store the timestamp of last time enter the Wechat SNS page
    static final boolean[] consentForm = {false}; // Store the timestamp of last time enter the Wechat SNS page

    /*
        Represent which value did user selected, the content of intervention varied according to user's value
        value[0] for plain value
        value[1] for discipline value
        value[2] for health value
        value[3] for order value
        value[4] for persistence value
        value[5] for responsible value
        value[6] for self-awareness value
        value[7] for self-care value
     */
    static final boolean[] userValue = {false, true, false, false, false, false, false, false};
    // Text for values, can be mapped to the userValue variable above
    static final String[] values = {"Plain", "Self-control", "Fitness", "Order", "Persistence", "Responsibility", "Self-awareness", "Self-care"};

    // Text for instruct user to set their value.
    static final String[][][] value_setting_cn = {
            // Text of the name of values
            {
                    {"Discipline"},
                    {"Health"},
                    {"Order"},
                    {"Persistence"},
                    {"Responsibility"},
                    {"SelfAwareness"},
                    {"SelfCare"}
            },
            // Description of values
            {
                    // Figures in [1] and [2] represent the text of value which will be highlighted
                    {"Self-control:\nto act in accordance with my own ideals"
                            , "0", "12"},
                    {"Fitness:\nto maintain or improve my physical and mental health"
                            , "0", "7"},
                    {"Order:\nto be orderly and organized"
                            , "0", "5"},
                    {"Persistence:\nto continue resolutely, despite problems or difficulties"
                            , "0", "11"},

                    {"Self-awareness:\nto be aware of my own thoughts, feelings and actions"
                            , "0", "14"},
                    {"Self-care:\nto look after my well-being and get my needs met"
                            , "0", "9"},
                    {"Responsibility:\nto be responsible and accountable for my actions"
                            , "0", "14"}
            }
    };

    /*
        Text content for interventions according to user's value
        Figures in [1] and [2] of every text represent the text of value which will be highlighted
        interventionContentComponent[0] for discipline value
        interventionContentComponent[1] for health value
        interventionContentComponent[2] for order value
        interventionContentComponent[3] for persistence value
        interventionContentComponent[4] for responsible value
        interventionContentComponent[5] for self-awareness value
        interventionContentComponent[6] for self-care value
        interventionContentComponent[7] for action during work
        interventionContentComponent[8] for action before sleep

     */
    static final String[][][] interventionContentComponent_value = {
            {},
            {
                    {"I value self control", "8", "20"},
                    {"I think self control is important", "8", "20"},
                    {"I value self control", "8", "20"},
            },
            {
                    {"I think health is important", "8", "14"},
                    {"I cherish health", "10", "16"},
                    {"I value health", "8", "14"}
            },
            {
                    {"Being organized is important to me", "0", "15"},
                    {"Being organized is important to me", "0", "15"},
                    {"I focus on being organized", "11", "26"},
                    {"I pay attention to orderly", "19", "26"},
                    {"I believe that being organized is important", "15", "30"},
                    {"I believe order is important", "10", "15"},
                    {"I believe I can be organized", "16", "28"},
                    {"I believe I can be in order", "22", "27"},
                    {"I believe I am organized", "15", "24"},
                    {"I believe I am in order", "18", "23"},
                    {"I believe I can be organized", "16", "28"},
                    {"I believe I can be in order", "22", "27"},
                    {"I believe I can be organized", "19", "28"},
                    {"I believe I can be in order", "22", "28"},
                    {"I value being organized", "8", "23"},
                    {"I value orderliness", "8", "19"},
                    {"I know that being organized is important", "12", "27"},
                    {"I know that order is important", "12", "17"},
                    {"I know I can be organized", "16", "25"},
                    {"I know I can be in order", "16", "24"},
                    {"I know I am organized", "12", "21"},
                    {"I know I am in order", "12", "20"},
                    {"I know I can be organized", "16", "25"},
                    {"I know I can be in order", "16", "24"},
                    {"I know I can be organized", "16", "25"},
                    {"I know I can be in order", "16", "24"},
                    {"I think being organized is important", "8", "23"},
                    {"I think order is important", "8", "13"},
                    {"I think I can be organized", "17", "26"},
                    {"I think I can be in order", "17", "25"},
                    {"I think I am organized", "13", "22"},
                    {"I think I am in order", "13", "21"},
                    {"I think I can be organized", "17", "26"},
                    {"I think I can be in order", "17", "25"},
                    {"I think I can be organized", "17", "26"},
                    {"I think I can be in order", "17", "25"},
                    {"I value being organized", "8", "23"},
                    {"I value orderly", "8", "15"}
            },
            {
                    {"Stability is important to me", "0", "9"},
                    {"Insistence on goals is important to me", "0", "19"},
                    {"I pay attention to firmness", "19", "27"},
                    {"I pay attention to stick to the goal", "19", "36"},
                    {"I believe firmness is important", "10", "18"},
                    {"I believe it is important to stick to the goal", "29", "46"},
                    {"I believe I can be firm", "19", "23"},
                    {"I believe I can stick to the goal", "16", "33"},
                    {"I believe I am firm", "15", "19"},
                    {"I believe I am a firm person", "17", "28"},
                    {"I believe I stick to my goals", "12", "29"},
                    {"I believe I can be firm", "16", "23"},
                    {"I believe I can stick to the goal", "16", "33"},
                    {"I believe I can be firm", "16", "23"},
                    {"I believe I can stick to the goal", "16", "33"},
                    {"I value firmness", "8", "16"},
                    {"I value sticking to goals", "8", "25"},
                    {"I know that firmness is important", "12", "20"},
                    {"I know that sticking to the goal is important", "12", "32"},
                    {"I know I can be firm", "13", "20"},
                    {"I know I can stick to the goal", "13", "30"},
                    {"I know I am firm", "12", "16"},
                    {"I know I am a firm person", "14", "18"},
                    {"I know I stick to my goals", "9", "26"},
                    {"I know I can be firm", "13", "20"},
                    {"I know I can stick to the goal", "13", "30"},
                    {"I know I can be firm", "13", "20"},
                    {"I know I can stick to the goal", "13", "30"},
                    {"I think firmness is important", "8", "16"},
                    {"I think it is important to stick to the goal", "27", "44"},
                    {"I think I can be firm", "14", "21"},
                    {"I think I can stick to the goal", "14", "31"},
                    {"I think I am firm", "13", "17"},
                    {"I think I am a firm person", "13", "26"},
                    {"I think I stick to my goals", "10", "27"},
                    {"I think I can be firm", "10", "21"},
                    {"I think I can stick to the goal", "10", "30"},
                    {"I think I can be firm", "10", "21"},
                    {"I think I can stick to the goal", "10", "30"},
                    {"I value firmness", "8", "16"},
                    {"I attach importance to sticking to goals", "23", "40"}
            },
            {
                    {"Being responsible for yourself is important to me", "0", "30"},
                    {"I pay attention to being responsible for myself", "19", "47"},
                    {"I focus on self-responsibility", "11", "30"},
                    {"I believe it is important to be responsible for myself", "29", "54"},
                    {"I believe I can be responsible for myself", "16", "40"},
                    {"I believe I am responsible for myself", "15", "37"},
                    {"I believe I can be responsible for myself", "16", "40"},
                    {"I believe I can be responsible for myself", "16", "40"},
                    {"I believe I can be responsible for myself", "16", "40"},
                    {"I believe that self-responsibility is important", "15", "34"},
                    {"I value being responsible for myself", "8", "36"},
                    {"I value self-responsibility", "8", "27"},
                    {"I know that being responsible for myself is important", "12", "40"},
                    {"I know I can be responsible for myself", "13", "38"},
                    {"I know I am responsible for myself", "12", "34"},
                    {"I know I can be responsible for myself", "13", "38"},
                    {"I know I can be responsible for myself", "13", "38"},
                    {"I know I can be responsible for myself", "13", "38"},
                    {"I know that self-responsibility is important", "12", "31"},
                    {"I think it is important to be responsible for myself", "27", "52"},
                    {"I think I can be responsible for myself", "14", "39"},
                    {"I think I am self-responsible", "13", "29"},
                    {"I think I can be responsible for myself", "14", "39"},
                    {"I think I can be responsible for myself", "14", "39"},
                    {"I think I can be responsible for myself", "14", "39"},
                    {"I think self-responsibility is important", "8", "27"},
                    {"I value being responsible for myself", "8", "36"},
                    {"I value self-responsibility", "8", "27"},
                    {"Self-responsibility is important to me", "0", "19"}
            },
            {
                    {"I pay attention to being self-aware", "19", "35"},
                    {"I pay attention to self-awareness", "19", "33"},
                    {"I believe I am self-conscious", "15", "29"},
                    {"I believe I can be self-aware", "15", "29"},
                    {"I believe that self-awareness is important", "15", "29"},
                    {"I believe that self-awareness is important", "15", "29"},
                    {"I value self-awareness", "8", "22"},
                    {"I value self-awareness", "8", "22"},
                    {"I know I am self-conscious", "12", "26"},
                    {"I know I can be self-aware", "12", "26"},
                    {"I know that self-awareness is important", "12", "26"},
                    {"I know that self-awareness is important", "12", "26"},
                    {"I think I am self-conscious", "13", "27"},
                    {"I think I can be self-aware", "13", "27"},
                    {"I think it is important to have self-awareness", "32", "46"},
                    {"I think self-awareness is important", "8", "22"},
                    {"I value self-awareness", "8", "22"},
                    {"I value self-awareness", "8", "22"},
                    {"It is important to me to have self-awareness", "30", "44"},
                    {"Self-awareness is important to me", "0", "14"}
            },
            {
                    {"Caring about yourself is important to me", "0", "21"},
                    {"I care about myself", "2", "19"},
                    {"I pay attention to self-care", "19", "28"},
                    {"I believe that caring about yourself is important", "15", "36"},
                    {"I believe I can care about myself", "16", "33"},
                    {"I believe I can care about myself", "16", "33"},
                    {"I believe I care about myself", "12", "29"},
                    {"I believe I care about myself", "12", "29"},
                    {"I believe I can care about myself", "16", "33"},
                    {"I believe I can care about myself", "16", "33"},
                    {"I believe I can care for myself", "16", "31"},
                    {"I believe I can care for myself", "16", "31"},
                    {"I believe that self-care is important", "15", "24"},
                    {"I care about myself", "2", "19"},
                    {"I value self-care", "8", "17"},
                    {"I know that caring about myself is important", "12", "31"},
                    {"I know I can care about myself", "13", "30"},
                    {"I know I can care about myself", "13", "30"},
                    {"I know I care about myself", "9", "26"},
                    {"I know I care about myself", "9", "26"},
                    {"I know I can care about myself", "13", "30"},
                    {"I know I can care about myself", "13", "30"},
                    {"I know I can care for myself", "13", "28"},
                    {"I know I can care about myself", "13", "30"},
                    {"I know that self-care is important", "12", "21"},
                    {"I think it is important to care about yourself", "27", "46"},
                    {"I think I can care about myself", "13", "31"},
                    {"I think I can care about myself", "13", "31"},
                    {"I think I care about myself", "10", "27"},
                    {"I think I care about myself", "10", "27"},
                    {"I think I can care about myself", "13", "31"},
                    {"I think I can care about myself", "13", "31"},
                    {"I think I can care about myself", "13", "31"},
                    {"I think I can care about myself", "13", "31"},
                    {"I think self-care is important", "8", "30"},
                    {"I value and care about myself", "12", "29"},
                    {"I value self-care", "8", "17"},
                    {"Self-care is important to me", "0", "9"}
            }
    };

    /*
        interventionContentComponent_action[0] for action during work
        interventionContentComponent_action[1] for action before sleep
     */
    static final String[][] interventionContentComponent_action_customize = {
            {"I can use the app less and [stay focus]", "27", "39"},
            {"I can use my phone less and [stay focus]", "28", "40"},
            {"I can leave the app and [stay focus]", "24", "36"},
    };

    // Persuasive text about the action user should take to avoid overuse of smartphone
    static final String[][] interventionContentComponent_action = {
            {
                    "I will concentrate on doing things and close the app",
                    "I will concentrate on doing things and play less on my mobile phone",
                    "I will concentrate on doing things and use my mobile phone less",
                    "I will concentrate on doing things and watch my phone less",
                    "I will concentrate on doing things and put down my phone",
                    "I will concentrate on doing things and exit the app",
                    "I will focus on doing things and close the app",
                    "I will focus on doing things and play less on my mobile phone",
                    "I will focus on doing things and use less mobile phones",
                    "I will concentrate on doing things and watch my phone less",
                    "I will concentrate on doing things and put down my phone",
                    "I will concentrate on doing things and exit the app",
                    "I will focus on doing things and close the application",
                    "I will focus on doing things and play less on my mobile phone",
                    "I will focus on doing things and use less mobile phones",
                    "I will focus on doing things and watch my phone less",
                    "I will focus on doing things and put down my phone",
                    "I will focus on doing things and exit the application",
                    "I will close the app and concentrate on doing things",
                    "I will close the app and focus on doing things",
                    "I will close the app and focus on doing things",
                    "I will close the application and focus attention",
                    "I will turn off the application to concentrate",
                    "I will play less on my mobile phone and concentrate on doing things",
                    "I will play less on my mobile phone and focus on doing things",
                    "I will play less on my mobile phone and focus on doing things",
                    "I will play less on my mobile phone and pay attention",
                    "I will play less mobile phone and concentrate",
                    "I will use my phone less and concentrate on doing things",
                    "I will use my phone less and focus on doing things",
                    "I will use my phone less and focus on doing things",
                    "I will use my mobile phone less and pay attention",
                    "I will use my phone less to concentrate",
                    "I will watch my phone less and concentrate on doing things",
                    "I will watch my phone less and focus on doing things",
                    "I will look less at my phone and focus on doing things",
                    "I will look at the phone less and pay attention",
                    "I will watch my phone less and concentrate",
                    "I will put down my phone and concentrate on doing things",
                    "I will put down my phone and focus on doing things",
                    "I will put down my phone and concentrate on doing things",
                    "I will put down my phone and focus on it",
                    "I will put down my phone and concentrate",
                    "I will quit the app and concentrate on doing things",
                    "I will quit the app and focus on doing things",
                    "I will quit the app and focus on doing things",
                    "I will quit the application to focus attention",
                    "I will quit the application to concentrate"
            },
            {
                    "I will close the app and prepare to rest",
                    "I will close the app and prepare to sleep",
                    "I will close the app and rest early",
                    "I will close the app and go to bed early",
                    "I will close the app and rest early",
                    "I will close the app and go to bed early",
                    "I will be ready to take a break and close the app",
                    "I will take a break and play less on my mobile phone",
                    "I will take a break and use my mobile phone less",
                    "I will take a break and watch my phone less",
                    "I will be ready to rest and put down my phone",
                    "I will be ready to take a break and exit the application",
                    "I will be ready to sleep and close the app",
                    "I will be ready to sleep and play less on my mobile phone",
                    "I will prepare to sleep and use my mobile phone less",
                    "I will prepare to sleep and watch my phone less",
                    "I will prepare to sleep and put down my phone",
                    "I will be ready to sleep and exit the app",
                    "I will play less on my mobile phone and prepare to rest",
                    "I will play less on my mobile phone and get ready to sleep",
                    "I will play less on my phone and rest earlier",
                    "I will play less on my mobile phone and go to bed earlier",
                    "I will play less on my mobile phone and rest earlier",
                    "I will play less on my mobile phone and go to bed earlier",
                    "I will use my phone less and prepare to rest",
                    "I will use my mobile phone less to prepare for bed",
                    "I will use my phone less and rest earlier",
                    "I will use my phone less and go to bed earlier",
                    "I will use my phone less and rest early",
                    "I will use my phone less and go to bed earlier",
                    "I will watch my phone less and prepare to rest",
                    "I will watch my phone less and get ready to sleep",
                    "I will watch my phone less and rest earlier",
                    "I will watch my phone less and go to bed earlier",
                    "I will watch my phone less and rest earlier",
                    "I will watch my phone less and go to bed earlier",
                    "I will put down my phone and prepare to rest",
                    "I will put down my phone and get ready to sleep",
                    "I will put down my phone and rest early",
                    "I will put down my phone to go to bed earlier",
                    "I will put down my phone and rest early",
                    "I will put down my phone and go to bed early",
                    "I will rest early and close the app",
                    "I will rest earlier and play less on my mobile phone",
                    "I will rest early and use my mobile phone less",
                    "I will rest early and watch my phone less",
                    "I will rest early and put down my phone",
                    "I will take a break and exit the app earlier",
                    "I will go to bed early and close the app",
                    "I will go to bed earlier and play less on my mobile phone",
                    "I will go to bed earlier and use my mobile phone less",
                    "I will go to bed earlier and watch my phone less",
                    "I will go to bed earlier and put down my phone",
                    "I will go to bed early and exit the app",
                    "I will rest early and close the app",
                    "I will rest early and play less on my mobile phone",
                    "I will rest early and use my mobile phone less",
                    "I will rest early and watch my phone less",
                    "I will rest early and put down my phone",
                    "I will take a break and exit the app soon",
                    "I will go to bed early and close the app",
                    "I will go to bed earlier and play less on my mobile phone",
                    "I will go to bed earlier and use my mobile phone less",
                    "I will go to bed early and watch my phone less",
                    "I will go to bed early and put down my phone",
                    "I will go to bed early and exit the app",
                    "I will quit the app and prepare to rest",
                    "I will quit the app and prepare to sleep",
                    "I will quit the app and rest early",
                    "I will quit the app and go to bed earlier",
                    "I will quit the app and rest early",
                    "I will quit the app and go to bed early"
            }
    };

    // Map the random int to strings which user will input
    static final Map<Integer,String> int2String = new HashMap<Integer,String>(){{
        this.put(1, "One");
        this.put(2, "Two");
        this.put(3, "Three");
        this.put(4, "Four");
        this.put(5, "Five");
        this.put(6, "Six");
        this.put(7, "Seven");
        this.put(8, "Eight");
        this.put(9, "Nine");
    }};

    static final String[] thoughtProvokingList = {
            " is important to my life?",
            " is important to me?",
            " is important to me?",
            " is important to me?",
            " is important to my life?",
            " is important to me?",
            " is important to me?",
            " is important to me?"
    };

    // Timeout Actions
    static final String ACTION_LOG_INTERVENTION = "ACTION_LOG_INTERVENTION";
    static final String ACTION_START_INTERVENTION = "ACTION_START_INTERVENTION";
    static final String ACTION_START_APPLICATION = "ACTION_START_APPLICATION";
    static final String ACTION_END_INTERVENTION = "ACTION_END_INTERVENTION";

    // NOTIFICATION IDs
    static final String SMARTPHONE_USE_PLUGIN_NOTIFICATION_CID = "smartphone_use_01";
    static final int SMARTPHONE_USE_PLUGIN_NOTIFICATION_ID = 101;
    static final String SMARTPHONE_USE_CRASH_NOTIFICATION_CID = "smartphone_use_crash_01";
    static final int SMARTPHONE_USE_CRASH_NOTIFICATION_ID = 102;
    static final String SMARTPHONE_USE_NO_APP_USAGE_X_HOURS_CID = "smartphone_use_no_app_usage_x_hours_01";
    static final int SMARTPHONE_USE_NO_APP_USAGE_X_HOURS_ID = 103;
    static final String SMARTPHONE_USE_SWITCH_DEBUG_CID = "smartphone_use_switch_debug_01";
    static final int SMARTPHONE_USE_SWITCH_DEBUG_ID = 104;

    // Constants about restricting user from use Wechat timeline and mini program
    final static Boolean WithPyq[] = {true};
    final static Boolean WithMini[] = {true};
    final static String WeChatPackageName = "com.tencent.mm";
    final static String[] WeChatActivities_with_both = new String[] {
            "com.tencent.mm/.plugin.appbrand.launching.AppBrandLaunchProxyUI",
            "com.tencent.mm/.plugin.finder.ui.FinderHomeUI",
            "com.tencent.mm/.plugin.sns.ui.SnsTimeLineUI"
    };
    final static String[] WeChatActivities_with_pyq = new String[] {
            "com.tencent.mm/.plugin.finder.ui.FinderHomeUI",
            "com.tencent.mm/.plugin.sns.ui.SnsTimeLineUI"
    };
    final static String[] WeChatActivities_with_mini = new String[] {
            "com.tencent.mm/.plugin.appbrand.launching.AppBrandLaunchProxyUI",
            "com.tencent.mm/.plugin.finder.ui.FinderHomeUI",
    };
    final static String[] WeChatActivities_without_both = new String[] {
            "com.tencent.mm/.plugin.finder.ui.FinderHomeUI",
    };

    // The list of APPs which manually blocked by user
    final static List<String> userBlackListApps = Arrays.asList(
    );
    // The list of APPs which in the default blacklist
    final static List<String> BlackListApps = Arrays.asList(
            "com.og.danjiddz",
            "com.jiuxianapk.ui",
            "com.tencent.tmgp.SevenHegemony",
            "com.joym.legendhero.yyb",
            "air.com.tencent.qqfarmios",
            "air.com.pocket.game.Tiny_Robber_Bob2",
            "com.telecom.video",
            "com.xiaomi.shop",
            "com.duomi.android",
            "net.huiguo.app",
            "com.netease.dwrg.nearme.gamecenter",
            "com.tencent.tmgp.ylm",
            "com.tencent.radio",
            "com.zol.android",
            "com.tencent.tmgp.coslegend",
            "com.vanchu.apps.guimiquan",
            "net.xinhuamm.mainclient",
            "com.tencent.pao",
            "com.tencent.minihd.qq",
            "com.hs.yjseller",
            "com.ss.android.article.lite",
            "com.skyplatanus.crucio",
            "com.xxjh.ttbp.Runningeveryday",
            "com.xiaomi.o2o",
            "com.tencent.tmgp.yxwdzzjy",
            "com.kugou.playerHDyy",
            "com.btime.bjtime",
            "com.tencent.tmgp.hcr2",
            "cn.soulapp.android",
            "com.fanliyouhuiquanlmw",
            "com.funcity.carsbattletwo",
            "com.outfit7.talkinggingerfree",
            "com.linkdeskstudio.popcat",
            "com.yunbu.arcadepool.tencent",
            "www.imxiaoyu.com.musiceditor",
            "com.sty.jixianmotuo.qq",
            "com.cashtoutiao",
            "com.sofunny.Sausage",
            "tv.acfundanmaku.video",
            "com.luckyboy.mmxing",
            "com.sdbean.werewolf",
            "com.biyao.fu",
            "com.tencent.tmgp.xcqykkk5",
            "com.tencent.tim",
            "com.qixiao.qrxs",
            "com.radishmobile.electricscreen",
            "com.tencent.tmgp.fish3d",
            "com.tencent.reading",
            "cn.com.qlwb.qiluyidian",
            "cn.TuHu.android",
            "com.dragon.ringtone",
            "com.sohu.qianfan",
            "cn.xiaochuankeji.zuiyouLite",
            "com.achievo.vipshop",
            "com.tencent.peng",
            "com.iqilu.ksd",
            "cn.longmaster.pengpeng",
            "com.duoduo.cailing",
            "com.tencent.swy",
            "com.ss.readpoem",
            "com.xmtj.mkz",
            "com.gov.cn",
            "com.theotino.chinadaily",
            "com.youku.phone",
            "com.tencent.tmgp.yys.zqb",
            "com.tencent.tmgp.jz",
            "com.duitang.main",
            "com.hupu.games",
            "com.vqs.iphoneassess",
            "com.dz.mfxsqj",
            "com.netease.onmyoji.uc",
            "com.kamitu.drawsth.standalone.free.android",
            "com.wallstreetcn.news",
            "com.tencent.qqgame",
            "com.rumtel.mobiletv",
            "com.tencent.tmgp.arrowio",
            "com.tuan800.tao800",
            "com.yinhan.hunter.uc",
            "com.miragine.MiragineWar",
            "com.mfp.jelly.yingyongbao",
            "com.tencent.tmgp.sggl",
            "io.dushu.fandengreader",
            "cn.kuwo.player",
            "cn.wejuan.reader",
            "com.jf.lkrj",
            "com.talkweb.mjkillmonsters.qq",
            "com.ximalaya.ting.lite",
            "com.forjuan.trial",
            "com.ifreetalk.ftalk",
            "com.tencent.tmgp.dfhii",
            "com.tencent.tmgp.snsgz",
            "com.huizheng.tcyyhz",
            "com.le123.ysdq",
            "com.sniper.activity",
            "com.tencent.tmgp.rxcq",
            "com.alibaba.android.babylon",
            "com.siyanhui.biaoqingme",
            "com.wodi.who",
            "com.droidhen.game.racingmoto",
            "com.tiange.miaolive",
            "com.tencent.Mtown",
            "com.tencent.tmgp.dhad",
            "com.bilibili.priconne.aligames",
            "com.mfp.jelly.oppo",
            "com.wbxm.icartoon",
            "tv.xiaoka.live",
            "com.kugou.fanxing",
            "com.qzone",
            "com.hnmoma.expression",
            "com.wali.live",
            "com.voicedragon.musicclient",
            "com.tencent.tmgp.cjjd",
            "com.wepie.wespy",
            "com.teamnet.hula",
            "air.fyzb3",
            "com.pfu.popstar",
            "com.baidu.searchbox.lite",
            "com.tencent.qqgame.xq",
            "com.jzyd.coupon",
            "com.cns.mc.activity",
            "com.husor.beibei",
            "org.zywx.wbpalmstar.widgetone.uex11364651",
            "com.ustwo.monumentvalleyzz",
            "com.halfbrick.fruitninjafree",
            "com.sankuai.meituan",
            "com.tencent.tmgp.dancingline",
            "com.tencent.tmgp.dtszjwd222",
            "com.m1905.mobilefree",
            "cn.mama.activity",
            "com.tencent.tgclub",
            "com.miHoYo.HSoDv22144.tencent",
            "com.devman.zhen.xiadiyu",
            "com.xinli.fm",
            "com.waqu.android.general_video",
            "com.sg.android.fish",
            "com.tencent.tmgp.wec",
            "com.zhifu.live",
            "com.faloo.BookReader4Android",
            "com.soulgame.bear",
            "oms.mmc.fortunetelling.measuringtools.naming",
            "com.shunlian.app",
            "com.bilibili.comic",
            "com.tencent.tmgp.bcbm",
            "com.touchtv.touchtv",
            "com.anzogame.coc",
            "com.soft.blued",
            "com.dddwan.summer.ewan.tencent",
            "com.netease.mc.nearme.gamecenter",
            "com.m4399.gamecenter",
            "com.android.comicsisland.activity",
            "com.tencent.xjcard",
            "com.nd.android.pandareader",
            "com.eyesthegame.eyes",
            "com.tencent.tmgp.dungeon22",
            "com.escape.feixiang",
            "com.zhtiantian.ChallengerTX",
            "com.netease.dwrg",
            "com.hi.voicechanger",
            "com.ruanmei.ithome",
            "com.tencent.now",
            "com.mianfeinovel",
            "com.weico.international",
            "com.youzu.bs.nearme.gamecenter",
            "com.ymall.presentshop",
            "com.carrot.carrotfantasy",
            "com.duokan.reader",
            "com.tianwen.jjrb",
            "com.xiaoao.car3d4.qq",
            "com.baidu.news",
            "com.taomee.molenew",
            "com.nice.main",
            "com.dianzhi.xianzhuan",
            "com.kugou.android.ktvapp",
            "com.sqage.sanguo",
            "com.bangbangce.mm",
            "com.papegames.nn4.cn",
            "com.max.xiaoheihe",
            "com.tencent.tmgp.sgame",
            "com.tencent.af",
            "com.bandaorongmeiti.news",
            "com.taobao.movie.android",
            "com.gwd.mnsjhw",
            "com.oupeng.mini.android",
            "com.immomo.momo",
            "com.mobimirage.android.Legend.pps",
            "com.tencent.tmgp.fgo",
            "com.ting.mp3.android",
            "com.netease.my.nearme.gamecenter",
            "com.blackfish.app.ui",
            "com.netease.pm02.nearme.gamecenter",
            "com.jin10",
            "com.icloudzone.DeathMoto2",
            "com.tencent.tmgp.bh3",
            "com.tencent.tmgp.rxjhbj",
            "com.xiaoenai.app",
            "cn.kuwo.tingshu",
            "com.netease.cloudmusic",
            "cn.cntvnews",
            "com.tencent.tgp",
            "com.tencent.tmgp.speedmobile",
            "cn.cntv",
            "com.tencent.tmgp.NBA",
            "com.baoruan.lewan",
            "com.ifeng.android",
            "com.yicai.news",
            "com.chaozh.iReaderFree15",
            "com.jiemian.news",
            "com.vv51.mvbox",
            "com.xtc.watch",
            "com.zplay.migupopstar",
            "com.zhejiangdaily",
            "com.hnzx.hnrb",
            "com.hzpd.xmwb",
            "com.watsons.mobile",
            "com.tencent.tmgp.leju.ssyyg",
            "com.netease.hyxd.nearme.gamecenter",
            "com.outfit7.talkingtom",
            "com.anzogame.game",
            "cn.kuwo.kwmusichd",
            "com.blingstorm.biscuit",
            "com.tencent.tmgp.minitech.miniworld",
            "com.tencent.tmgp.evol",
            "com.tencent.qqlite",
            "com.nc.dragon.robot",
            "com.xd.ttdbl.uc",
            "com.tongzhuo.tongzhuogame",
            "com.kidswant.ss",
            "com.Tiange.ChatRoom",
            "com.yunbu.magicprincess.tencent",
            "com.tencent.tmgp.txsgsj",
            "com.rayjoy.android.tank.ruanyou",
            "com.happy.chinesechessfsg",
            "com.jianshu.haruki",
            "com.ssxg.cheers",
            "com.new.ring",
            "com.sina.weibolite",
            "com.yodo1.skisafari2.TXYYB_01",
            "com.huanqiu.news",
            "com.linkedin.android",
            "com.onesoft.app.Tiiku.Duia.KJZ",
            "com.firemaplegames.thelostcity",
            "com.chengdudaily.activity",
            "com.mallestudio.gugu.app",
            "com.tencent.tmgp.hse",
            "com.tencent.tmgp.g12000128",
            "com.qinhe.ispeak",
            "com.android.app.quanmama",
            "com.cdsb.newsreader",
            "com.tencent.tmgp.weile.gymaj",
            "com.rednet.moment",
            "com.qqgame.happymj",
            "com.budejie.mimi",
            "com.miHoYo.HSoDv22144.uc",
            "com.fairytale.fortune",
            "com.huuhoo.mystyle",
            "com.tencent.tmgp.hkddz",
            "com.rockstargames.gtavc",
            "com.tp.ttgame.jiutian",
            "lqs.kaisi.kdlianliankan",
            "air.tv.douyu.android",
            "com.netease.onmyoji.nearme.gamecenter",
            "com.ximalaya.ting.android",
            "com.tencent.tmgp.cjad",
            "com.tencent.tmgp.TXHD.sqsy",
            "com.tencent.tmgp.dfzj",
            "cn.com.shouji.market",
            "com.teayelp.whereareyoumysister",
            "com.aligames.sgzzlb.aligames",
            "com.tencent.tmgp.supercell.brawlstars",
            "com.tencent.Qfarm",
            "com.dzwww.sd.android",
            "com.xiaoao.dinopets.qq",
            "com.tencent.tmgp.dwrg",
            "com.meelive.ingkee",
            "com.xiaoao.riskSnipe.nqq",
            "com.leixun.taofen8",
            "com.supercell.clashofclans.nearme.gamecenter",
            "com.kwai.sogame",
            "com.nacai.bocai",
            "com.kwai.livepartner",
            "com.wannengbxq.qwer",
            "com.supercell.boombeach.bb",
            "bmvkf.r0g2zf.bmcrz",
            "com.nfdaily.nfplus",
            "com.tencent.tmgp.mqwsgzz",
            "com.kuaikan.comic",
            "com.tencent.tmgp.ledou.mhhy",
            "org.tinghood.TpsForMobile",
            "com.mianfei.book",
            "com.adobe.flashplayer",
            "com.waterise.wr011",
            "com.laoyuegou.android",
            "cn.com.modernmedia.businessweek",
            "com.leixun.haitao",
            "com.tuhao.laosiji",
            "com.baozoumanhua.android",
            "com.tencent.JWX",
            "com.tencent.weishi",
            "com.miHoYo.bh3.nearme.gamecenter",
            "com.tencent.tmgp.l10",
            "com.aipai.android",
            "danxian.pop_star.gzlt",
            "com.tencent.tmgp.xlwysy",
            "com.netease.cartoonreader",
            "com.cmcm.arrowio",
            "com.tencent.tmgp.sxddc",
            "com.tencent.tmgp.wcdzzqqqq",
            "com.yunxi.bell",
            "com.buluobang.iguitar",
            "sh.lilith.dgame.uc",
            "cn.gmw.cloud",
            "com.imusic.iting",
            "com.tencent.tmgp.bairimeng.snake",
            "com.tencent.tmgp.zgtz",
            "app.podcast.cosmos",
            "com.jaizee.tunnelvision",
            "com.ringcrop.ku",
            "cn.changsha.xczxapp",
            "com.naquatic.guncraft",
            "com.wedobest.shudu",
            "com.invictus.impossiball",
            "com.ttzx.app",
            "com.tencent.tmgp.afcl",
            "com.xianlai.mahjonghainan",
            "com.netease.nieapp",
            "com.tencent.tmgp.qtdl3d",
            "com.guagua.guagua",
            "com.mujirenben.liangchenbufu",
            "com.blueocean.musicplayer",
            "com.blackbean.cnmeach",
            "com.dangdang.buy2",
            "com.bilibili.blhx.uc",
            "com.ushaqi.zhuishushenqi",
            "com.bokecc.dance",
            "com.qqgame.hlddz",
            "com.tencent.WeFire",
            "com.showself.ui",
            "com.a3733.gamebox",
            "tv.pps.mobile",
            "com.iflytek.ringdiyclient",
            "com.qiyi.video",
            "com.hcg.cok.uc",
            "com.tinder",
            "com.tencent.mtt",
            "com.sumavision.talktv2",
            "com.gionee.client",
            "com.pufei.gxdt",
            "com.dianping.v1",
            "com.shopping.mall.kuayu",
            "com.llg.funnygun",
            "com.lotogram.wawaji",
            "cn.emagsoftware.gamehall",
            "com.jj.shows",
            "com.jrtd.mfxszq",
            "com.anzogame.hs",
            "com.xk.span.zutuan",
            "com.anzogame.wzry",
            "com.wodidashi.avalon",
            "cn.edusign.chongqingunion",
            "com.yinhan.shenmo.tencent",
            "com.yue.ai.yuanfen",
            "com.tencent.tmgp.cqzj",
            "com.tencent.gamehelper.speed",
            "com.screeclibinvoke",
            "com.qiangfeng.mpisoft.parallel_worlds",
            "com.tencent.tmgp.pvz2tx",
            "com.tencent.weread",
            "com.tencent.tmgp.jymjsj666",
            "com.cubic.autohome",
            "com.sxiaoao.feijidazhan2dx",
            "com.ss.android.ugc.aweme.lite",
            "klb.android.lovelivecn",
            "com.tencent.tmgp.cmcm.zmjjkillshotbravo",
            "com.yuehuayueyou.app",
            "com.tencent.qt.qtl",
            "com.ss.android.article.video",
            "com.wepie.snake",
            "com.sgshd.nearme.gamecenter",
            "com.yxiaoao.car3d",
            "com.netease.yanxuan",
            "com.audio.tingting",
            "com.wangzhi.MaMaHelp",
            "com.minitech.miniworld.nearme.gamecenter",
            "cn.banshenggua.aichang",
            "com.renren.mobile.android",
            "cn.xiaochuankeji.tieba",
            "com.xxsyread",
            "com.mango.hnxwlb",
            "com.shoujiduoduo.ringtone",
            "com.reawake.game.llpoker",
            "com.gwsoft.imusic.controller",
            "com.luhu.eshop",
            "com.naquatic.monstercrafter",
            "com.supercell.boombeach.uc",
            "org.ajmd",
            "com.gtw.sevn.game",
            "com.twitter.android",
            "com.longyuan.zzq.aligames",
            "com.esbook.reader",
            "com.tencent.qgame",
            "com.tencent.qqmusicpad",
            "com.u17.comic.phone",
            "com.businessvalue.android.app",
            "com.tencent.tmgp.mhxy.sqsy",
            "com.tencent.tmgp.kxdmj",
            "com.tencent.tmgp.WePop",
            "com.vodigitalarts.RallyRacerDrift2014",
            "com.ishugui",
            "com.taoche.qctt",
            "com.martian.ttbook",
            "com.smzdm.client.android",
            "com.royalgame.t2048",
            "com.xingin.xhs",
            "Ugame.ProjectA15.MM_3DLTZJ",
            "com.nearme.gamecenter.ddz.nearme.gamecenter",
            "cn.ishansong",
            "com.tencent.jgm",
            "com.pokercity.ddz",
            "com.muzhiwan.market",
            "com.hoge.android.chinablue",
            "com.joym.armorbear.yyb",
            "com.sina.weibo",
            "com.supercell.clashroyale.nearme.gamecenter",
            "com.pdragon.HD1010",
            "com.snailfighter.game.bigtower",
            "me.ddkj.cp",
            "com.android36kr.app",
            "com.yodo1.SkiSafari.TXYYB_01",
            "oms.mmc.fortunetelling",
            "com.zbx.ct.tvzhibo",
            "cn.jj.hall",
            "com.aim.racing",
            "com.lanjinger.choiassociatedpress",
            "com.ijinshan.browser",
            "com.happyelements.AndroidAnimal.qq",
            "com.racergame.cityracing3d",
            "com.ztgame.bob",
            "com.joygames.chinamj",
            "com.sohu.sohuvideo",
            "com.jsbc.lznews",
            "com.letv.android.client",
            "cn.qiang7.user",
            "com.rayjoy.android.tank.kkk5",
            "com.pla.daily",
            "com.luojilab.player",
            "com.taobao.etao",
            "com.happyelements.AndroidAnimal",
            "com.sina.app.weiboheadline",
            "com.kascend.chushou",
            "com.sinyuee.kingwar",
            "com.gamedo.ZombieTerminator",
            "com.tencent.tmgp.txpvzwjbmidas",
            "com.ovelin.guitartuna",
            "com.xunlei.cloud",
            "com.yy.huanju",
            "com.bgames.android.busjk",
            "com.pdragon.new2048",
            "com.driftbottle.app",
            "com.sohu.newsclient",
            "com.firechain.topInfo",
            "com.husor.beidian",
            "com.clou.sns.android.anywhered",
            "com.dangdang.reader",
            "com.soco.veggies3_tencent",
            "com.app.hero.ui",
            "com.huanyin.magic",
            "com.wuba.zhuanzhuan",
            "com.news.shangyounews",
            "com.dianchou.dcw",
            "com.itcode.reader",
            "com.tencent.tmgp.msbjjby",
            "com.tencent.tmgp.hxjysy",
            "com.lokinfo.android.gamemarket.mmshow",
            "com.bilibili.deadcells.mobile.aligames",
            "com.globalscanner",
            "com.zh.fs",
            "com.tencent.tmgp.qinsmoon",
            "com.tencent.tmgp.cokqq",
            "com.shanbay.news",
            "com.tencent.tmgp.zrd.lbjzlqytxyyb",
            "com.kugou.android.ringtone",
            "com.haowai.app.hwapp",
            "com.tiexue.mobile.topnews",
            "com.maihan.tredian",
            "com.smile.gifmaker",
            "com.xiaoshijie.sqb",
            "com.wodidashi.wolf",
            "com.cmvideo.migumovie",
            "com.duowan.groundhog.mctools",
            "com.shihun.berryrush",
            "cn.com.kuting.activity",
            "com.ovilex.bussimulator3d",
            "com.mianfeia.book",
            "com.tencent.tmgp.yinhan.skzh",
            "com.xfplay.play",
            "com.qk.qingka",
            "com.haiqiu.jihai",
            "cn.myhug.baobao",
            "com.hisunflytone.android",
            "com.UCMobile",
            "com.qingyii.mammoth",
            "com.netease.newsreader.activity",
            "im.yixin",
            "com.taojin.dungeon2.aligames",
            "com.tencent.tmgp.cod",
            "com.book2345.reader",
            "com.oppa.qz1yuan",
            "com.ruguoapp.jike",
            "com.east2d.everyimage",
            "com.tencent.tmgp.dfh3",
            "com.yiyou.ga",
            "com.tencent.game.VXDGame",
            "com.huizheng.fjyh",
            "com.tencent.tmgp.carrot2",
            "com.tencent.tmgp.pubgmhd",
            "com.tencent.tmgp.dragonball",
            "com.ifeng.fhdt",
            "com.xiaodao.jiemeng",
            "com.mrkj.sm",
            "com.netease.x19",
            "com.xunmeng.pinduoduo",
            "com.thestore.main",
            "com.twentyfirstcbh.epaper",
            "com.cmcm.gamemaster",
            "com.tencent.tmgp.wooduan.ssjj",
            "com.sina.news",
            "com.hunantv.imgo.activity",
            "com.hkzr.vrnew",
            "com.bf.sgs",
            "com.yuanfen.main",
            "com.yidian.xiaomi",
            "com.imangi.templerun2",
            "com.tencent.tmgp.sparklykey.qinsmoon",
            "com.boxring",
            "com.bilibili.fgo.uc",
            "com.funshion.video.mobile",
            "com.playkp.firep",
            "com.fanli.android.apps",
            "com.yinhan.hunter.tx",
            "com.kankanews.kankanxinwen",
            "com.miguo.ui",
            "com.gta.real.gangster.crime100439",
            "com.qire.manhua",
            "com.chongdingdahui.app",
            "com.xingjiabi.shengsheng",
            "com.baidu.yuedu",
            "com.lechuan.midunovel",
            "com.netease.sky.nearme.gamecenter",
            "com.lectek.android.sfreader",
            "com.outfit7.mytalkinghank",
            "com.tencent.tmgp.seal",
            "com.kmxs.reader",
            "com.rovio.angrybirds.qq",
            "com.tencent.tmgp.invasionqq",
            "com.mogujie",
            "com.songheng.eastnews",
            "com.netease.l10.nearme.gamecenter",
            "com.diyidan",
            "com.tjmilian.shanpei",
            "net.hybz",
            "com.tencent.tmgp.kaopu.dsgl",
            "com.coolsnow.qqface",
            "com.duowan.mobile",
            "com.tencent.karaoke",
            "com.tencent.gamehelper.smoba",
            "com.tencent.mobileqq",
            "com.outfit7.mytalkingtomfree",
            "com.tencent.tmgp.tx",
            "com.douban.radio",
            "com.cctv.cctv5ultimate",
            "com.ninexiu.sixninexiu",
            "bubei.tingshu",
            "com.changba",
            "com.shizhuang.duapp",
            "com.tudou.android",
            "com.meitu.meipu",
            "com.tencent.tmgp.sgcs",
            "com.blizzard.wtcg.hearthstone",
            "com.headupgames.bridgeconstructor",
            "com.pom.sgz",
            "com.changwan.giftdaily",
            "com.tencent.news",
            "com.peopledailychina.activity",
            "com.tencent.tmgp.com.coco.wlsswz",
            "com.tencent.tmgp.qjnn",
            "com.babycloud.hanju",
            "com.hw.okm",
            "air.com.tencent.qqpasture",
            "sogou.mobile.explorer",
            "com.cissy.zels",
            "com.shenyuan.militarynews",
            "com.mianfeizs.book",
            "com.babychat",
            "com.adobe.reader",
            "com.gameabc.zhanqiAndroid",
            "com.lqs.kaisi.bill",
            "com.ada.ls",
            "com.tencent.tmgp.ddtank",
            "fm.qingting.qtradio",
            "com.kurogame.haru.aligames",
            "com.zzlt.mpet",
            "com.chineseall.singlebook",
            "com.moqu.dongdong",
            "com.mia.miababy",
            "com.knight.union",
            "com.tencent.tmgp.tstl",
            "com.ecapycsw.onetouchdrawing",
            "com.brianbaek.popstar",
            "com.hhly.mlottery",
            "com.pokercity.bydrqp.tencent",
            "com.tencent.tmgp.leju.xbkp",
            "com.tencent.djcity",
            "com.loli.loli",
            "com.zr8169.live",
            "com.qqgame.mic",
            "com.gsmdtiostrtrck.truckdriving3droadspeddd",
            "com.quark.browser",
            "com.anysoft.tyyd",
            "com.mobi.screensaver.publish",
            "com.anzogame.cf",
            "com.netease.ma71",
            "com.toudiannews.android",
            "com.erdo.android.FJDXCartoon",
            "com.yoho",
            "com.taobao.taobao",
            "com.facebook.katana",
            "com.tencent.tmgp.cf",
            "cn.mucang.android.qichetoutiao",
            "com.weile.game",
            "com.wondertek.miguaikan",
            "com.bairimeng.dmmdzz.nearme.gamecenter",
            "net.mobigame.zombietsunami",
            "com.huizheng.ffjmy",
            "com.fm.aiyinsitan",
            "com.baidu.netdisk",
            "com.tencent.tmgp.netcraftyouyi",
            "com.tencent.tmgp.limboworks.honorofcup",
            "com.nodemusic",
            "com.tencent.tmgp.ssqyz",
            "com.yinhan.shenmo.uc",
            "com.tencent.tmgp.DDD2",
            "com.tencent.lzhx",
            "com.aixuedai.axd",
            "com.vg.limosim",
            "com.polarbit.rthunder2",
            "com.tencent.tmgp.yxzj",
            "com.outfit7.mytalkingangelafree",
            "com.ss.android.ugc.live",
            "com.tencent.tmgp.sgzr",
            "com.Android56",
            "com.gome.eshopnew",
            "com.yixia.videoeditor",
            "com.knight.union.mi",
            "cn.com.pcauto.android.browser",
            "com.tsw.starcrush.yyb",
            "com.cctv.caijing",
            "com.shihun.offroadracing3d",
            "tv.danmaku.bili",
            "com.gamestar.pianoperfect",
            "com.tencent.tmgp.dtszj",
            "com.pdragon.fivechess",
            "lqs.kaisi.ddp",
            "com.juanpi.ui",
            "com.chaozh.iReaderFree",
            "com.taobao.idlefish",
            "com.dianping.t",
            "com.xiaoji.emulator",
            "com.evideo.MobileKTV",
            "yong.yunzhichuplayer",
            "com.koogame.SangoSlayer_TX",
            "com.hypergryph.arknights",
            "com.dongqiudi.news",
            "com.tencent.tmgp.qzyx",
            "com.icswb.ChangshaInHand",
            "com.c2vl.kgamebox",
            "com.tencent.tmgp.dtszjwd666",
            "com.tttj98.ttm",
            "com.tencent.tv.qie",
            "com.witmob.newsdigest",
            "com.kugou.tv.android",
            "com.joym.bearsadventure.yingyongbao",
            "com.sensedevil.VTT",
            "com.lanjingren.ivwen",
            "com.psd",
            "com.tencent.tmgp.yzr2",
            "io.liuliu.music",
            "com.netease.wyclx",
            "com.nowscore",
            "com.baidu.tieba",
            "com.tencent.qqsports",
            "com.worldyy.qq.app",
            "com.oppo.cameracom.android.ctsxinwen",
            "com.chengzivr.android",
            "com.storm.smart",
            "com.miHoYo.bh3.uc",
            "com.lashou.groupurchasing",
            "com.bf.sgs.hdexp",
            "com.sincetimes.games.worldship",
            "com.zhongduomei.rrmj.society",
            "com.tencent.tmgp.bydr3dx",
            "com.tencent.qqmusic",
            "com.tencent.tmgp.lsmfy",
            "com.tencent.feiji",
            "wnspbfq.app.ggplayer",
            "com.ifeng.newvideo",
            "com.ifeimo.videoeditor",
            "com.shoujiduoduo.dj",
            "com.sup.android.superb",
            "com.baidu.iknow",
            "com.dou_pai.DouPai",
            "org.cocos2d.fishingjoy3",
            "com.tencent.tmgp.jxqy",
            "com.tencent.tmgp.yongyong.zjz",
            "com.quan.taotaoquan",
            "com.baile.fish",
            "com.tencent.pocket",
            "com.qiyi.video.pad",
            "com.djinnworks.StickmanBasketball",
            "com.tencent.tmgp.jpzmg",
            "com.tencent.tmgp.rollingsky",
            "me.hypertext.local.jiong2",
            "com.qidian.QDReader",
            "com.tencent.tmgp.awlzw",
            "com.wepie.snake.new.mi",
            "org.vv.gameCell",
            "com.kiloo.subwaysurf",
            "com.tencent.research.drop",
            "com.tencent.tmgp.xxtjd",
            "com.tencent.tmgp.stzb",
            "com.classic.Pool",
            "com.tencent.tmgp.my.yyb",
            "com.tencent.tmgp.wansuiye",
            "com.huizheng.tcmmya",
            "me.ht.local.hot",
            "com.ycwb.android.ycpai",
            "com.moling.catchfish",
            "com.sixrpg.opalyer",
            "bf.sgs.hdexp",
            "com.lqlfreegames.grandtheftworlds",
            "com.ylmf.androidclient",
            "com.basestonedata.instalment",
            "com.bobo.splayer",
            "com.wepie.snake.tencent",
            "com.ourgame.mahjong.danji",
            "com.xiaoao.ultraman.qq",
            "com.tmall.wireless",
            "com.imlianai.mininovel",
            "cn.ibuka.manga.ui",
            "com.rovio.angrybirdsseasons",
            "com.tencent.tmgp.mhzxsy",
            "cn.youth.news",
            "com.tencent.tmgp.yzsnxyj",
            "com.tencent.tmgp.ttcz",
            "nn4.nearme.gamecenter",
            "com.buluobang.bangtabs",
            "cmccwm.mobilemusic",
            "com.naver.linewebtoon.cn",
            "com.youyuan.yhb",
            "com.tencent.qqlive",
            "com.tencent.clover",
            "com.timeweekly.timefinance",
            "com.culiu.qqpurchase",
            "com.ymatou.shop",
            "com.android.chrome",
            "com.lilithgames.rok.offical.cn",
            "com.fishgame2.qukong",
            "com.chineseall.reader",
            "com.zengame.zrttddz.nearme.gamecenter",
            "com.tencent.tmgp.wdsj666",
            "com.yxiaoao.car3d2",
            "com.rgbvr.wawa",
            "com.tencent.tmgp.ttwq",
            "com.netease.tom",
            "com.tencent.tmgp.pvz2hdtxyyb",
            "com.memezhibo.android",
            "cn.gamedog.terrariacomposbox",
            "com.tencent.king.candycrushsaga",
            "com.quanben.novel",
            "com.jjwxc.reader",
            "com.rinzz.noonedies",
            "com.yy.a.liveworld",
            "com.student.yuwen.yimilan",
            "com.lbaw.HotImportCustomCarRacing",
            "cn.mchang",
            "com.android.tutuerge",
            "com.shuqi.controller",
            "com.sing.client",
            "com.tencent.tmgp.zmxyol",
            "com.wangjiang.fjya",
            "com.crisisfire.android.uc",
            "com.fujian.daily",
            "com.tencent.tmgp.com.outfit7.talkingtomgoldrun",
            "com.wm.dmall",
            "com.ucmobile.lite",
            "com.ss.android.ugc.livelite",
            "com.tencent.tmgp.xishanju.mysy",
            "com.sogou.novel",
            "com.youyuan.yyhl",
            "com.sina.weibog3",
            "com.tencent.tmgp.cooeefish",
            "com.michael.think",
            "com.iflytek.womusicclient",
            "com.cnvcs.junqi",
            "com.huluxia.gametools",
            "com.tencent.tmgp.yqqskp",
            "com.xiaomi.youpin",
            "com.tencent.tmgp.zgjjhd",
            "com.tencent.tmgp.pocketmon",
            "com.zhibo.mm",
            "com.melot.meshow",
            "com.centurysoft.roboking",
            "com.digitalsky.girlsfrontline.cn.uc",
            "aye_com.aye_aye_paste_android",
            "com.yodo1.rodeo.TXYYB",
            "com.moling.buyu10002",
            "org.fungo.fungolive",
            "com.chenming.fonttypefacedemo",
            "com.lehai.ui",
            "com.sohomob.android.aeroplane_chess_battle_ludo_2",
            "com.mugua.mgvideo",
            "com.shihun.shooter3D",
            "com.netease.moba.aligames",
            "com.mykj.game.ddz",
            "com.soulgame.slithersg.tencent",
            "com.audiocn.karaok",
            "com.supercell.boombeach.wdj",
            "com.tencent.freestyle",
            "com.iqiyi.qixiu",
            "com.skymobi.fortconquer",
            "com.myzaker.ZAKER_Phone",
            "com.tencent.tmgp.yxsm",
            "com.p1.mobile.putong",
            "cn.com.talkweb.crazymagic.qq",
            "cn.zymk.comic",
            "me.yidui",
            "com.taobao.ju.android",
            "com.tencent.tmgp.tianmashikong.qj",
            "com.wondertek.paper",
            "com.tencent.tmgp.yongyong.clx",
            "com.konka.MultiScreen",
            "com.ss.android.ugc.aweme",
            "com.husor.mizhe",
            "com.zeptolab.ctrm.free.NonCMCC",
            "qsbk.app.remix",
            "com.taobao.live",
            "cn.voilet.musicplaypro",
            "com.bbgz.android.app",
            "com.kandian.vodapp",
            "com.tingwen",
            "com.netease.mrzh",
            "com.best.ringtone",
            "com.longzhu.tga",
            "com.alibaba.wireless",
            "com.yyk.knowchat",
            "com.fingersoft.hcr2.cn.tencent",
            "com.pplive.androidphone.sport",
            "com.huajiao",
            "com.thankcreate.StrangeAdventure",
            "com.etechs.eyee",
            "com.meiyou.youzijie",
            "com.martian.hbnews",
            "com.aligames.kuang.kybc.aligames",
            "com.tencent.tmgp.sm.hqg",
            "com.cmcc.cmvideo",
            "com.netease.uf",
            "com.tencent.tmgp.lwcsdldl3",
            "com.david.cl",
            "com.sohu.infonews",
            "com.caishi.cronus",
            "com.baihe",
            "com.wpd.game.popstar",
            "com.imaginer.yunji",
            "com.netease.ldxy.uc",
            "com.tencent.tmgp.playrix.township.chukong",
            "qsbk.app",
            "com.tencent.tmgp.zhanxian",
            "com.forthblue.pool",
            "com.icloudzone.TruckPark3D",
            "com.joym.bearfarm.yingyongbao",
            "com.wandafilm.app",
            "com.papegames.evol.aligames",
            "com.ibirdgame.zombieWarar.yingyongbao",
            "com.elinkway.infinitemovies",
            "tv.yixia.bobo",
            "com.tencent.tmgp.mtlbb",
            "dopool.player",
            "com.wglianmeng",
            "com.puyue.www.freesinglepurchase",
            "Fish.Game.Work",
            "com.xinglin.doudizhuad",
            "com.fenqile.fenqile",
            "com.jingdong.app.mall",
            "com.nanyibang.nomi",
            "com.ilongyuan.voez.uc",
            "com.jiecao.news.jiecaonews",
            "com.tencent.tmgp.wc3",
            "cn.shuangshuangfei",
            "com.secoo",
            "com.yixia.xiaokaxiu",
            "com.fanlitaolianmengw",
            "com.tencent.qqgame.qqhlupwvga",
            "com.duowan.kiwi",
            "com.kaola",
            "com.QQ.angel.webApp",
            "com.shinyv.cnr",
            "com.aikan",
            "com.qihoo.video",
            "com.hipu.yidian",
            "com.ihuayue.jingyu",
            "cn.kdqbxs.reader",
            "com.youyuan.jqyh",
            "com.yx",
            "com.culiukeji.huanletao",
            "com.tencent.tmgp.qqx5",
            "com.tencent.tmgp.jzsg",
            "com.ss.android.article.news",
            "com.xq.zysmb",
            "com.cplatform.surfdesktop",
            "com.tencent.tmgp.ahlm.sy37",
            "com.cf.xinmanhua",
            "com.suning.mobile.ebuy",
            "com.unicom.wopay",
            "cn.taxen.ziwei",
            "com.tencent.tmgp.dgsd",
            "com.itangyuan",
            "com.taobao.litetao",
            "com.iqiyi.ivrcinema.cb",
            "com.ijinshan.browser_fast",
            "com.join.android.app.mgsim",
            "cn.cri.chinaradio",
            "com.tencent.tmgp.ykdqddz",
            "com.tencent.tmgp.ddianle.lovedance",
            "com.xiangliyun.youxiu.xgyybfq",
            "com.miercnnew.app",
            "com.baidu.video",
            "com.gamestar.perfectpiano",
            "com.pplive.androidphone",
            "com.kugou.android",
            "com.ty.cfwf.qq",
            "com.tencent.mobileqqi",
            "com.thetisgames.mnkc2014",
            "com.jm.android.jumei",
            "com.gamedev.feng.mobiteos.trainx",
            "com.mewe.wolf",
            "com.netease.mrzh.nearme.gamecenter",
            "com.teamtopgame.sgmj",
            "com.tencent.tmgp.gbits.atm",
            "android.zhibo8",
            "com.ccdi.news",
            "com.seebaby",
            "com.lukou.youxuan",
            "cn.amazon.mShop.android",
            "com.sincetimes.fknsg",
            "com.game.BubbleShoot",
            "com.qq.reader",
            "com.bankcomm.maidanba",
            "com.tan8",
            "com.youku.crazytogether",
            "com.vmall.client",
            "com.mastercomlimited.cardriving_t",
            "com.meetstudio.app.Zither",
            "com.dazhihui.live",
            "com.appfun.feng.mpisoft.supernatural_evil_receptacle_full",
            "com.changdu",
            "com.tencent.tmgp.ultraman",
            "com.cis.jiangnan.coconut",
            "com.xs.fm",
            "com.cmge.dldldszl.nearme.gamecenter",
            "com.chaoxing.mobile",
            "com.hupu.shihuo",
            "com.tencent.tmgp.enjoymisgzj",
            "com.zz.georgeapk.date2013121703",
            "com.ea.simcitymobile.tx",
            "com.baidu.wenku",
            "cn.xianglianai",
            "com.tencent.tmgp.supercell.clashroyale",
            "com.tencent.cldts",
            "com.happyteam.dubbingshow",
            "com.ximigame.pengyouju",
            "com.huxiu",
            "com.happyelements.AndroidClover.www",
            "com.fingersoft.hillclimb",
            "com.kuaishou.nebula",
            "com.djbox.product",
            "com.shwatch.news",
            "com.lchr.diaoyu",
            "cool.score.android",
            "com.qiulianai.main",
            "com.tencent.tmgp.cats",
            "com.tencent.tmgp.zhuxian",
            "com.ogow.activity",
            "com.doudou.ysvideo",
            "com.tencent.tmgp.kof98",
            "com.zhenai.android",
            "net.iaround",
            "flipboard.cn",
            "com.hzsj.dsjy",
            "com.xiudang.jiukuaiyou.ui",
            "com.hermes.h1game.nearme.gamecenter",
            "com.wepie.snake.new",
            "com.anzogame.lol",
            "com.tuotuo.solo",
            "com.fosung.lighthouse",
            "com.cmstop.zett",
            "com.tencent.tmgp.hhw",
            "com.tencent.KiHan",
            "com.baidu.haokan",
            "com.dragon.read",
            "com.tencent.shootgame",
            "com.jiayuan",
            "com.netease.pris",
            "net.ghs.app",
            "com.taomee.molenew.mi",
            "com.yicen.ttkb",
            "com.yibasan.lizhifm",
            "com.mtime",
            "com.dragon.nes.adventure",
            "com.cwa.mojian",
            "com.tencent.tmgp.yjqy",
            "com.tencent.Q108",
            "com.ifext.news",
            "com.shiyue.fensigou",
            "com.tencent.mm",
            "com.jixiang.game",
            "com.happyplay.ddz",
            "com.tencent.tmgp.szr",
            "com.comic.manhuatai",
            "com.jiasoft.swreader",
            "com.songguoyhqw",
            "com.qiyi.video.reader",
            "com.tencent.tmgp.galasports.basketball",
            "com.douban.frodo",
            "com.koudai.weishop",
            "com.yitantech.gaigai",
            "cn.v6.sixrooms",
            "cn.dylovemm.csyh",
            "com.ifeng.news2",
            "com.sstar.stockstarnews",
            "com.tencent.tmgp.skymoons.seer",
            "com.yinyuetai.ui",
            "com.yunjibuyer.yunji",
            "com.baidu.searchbox",
            "com.ushaqi.zhuishushenqi.adfree",
            "com.tencent.tmgp.jnbg2",
            "com.zhihu.android",
            "com.baoear.baoer",
            "com.fingersoft.hillclimb.cn.noncmcc",
            "net.kairosoft.android.ninja_ja",
            "com.tencent.tmgp.hmzqfy",
            "com.huati",
            "com.tencent.tmgp.sgqyz",
            "com.ophone.reader.ui",
            "com.koudai.weidian.buyer",
            "gtem.roigzscpc.bbb",
            "com.tencent.tmgp.tew",
            "com.welove520.welove",
            "com.mobile.videonews.li.video",
            "com.tencent.tmgp.zqfy",
            "com.welove520.qqsweet",
            "com.huodao.hdphone",
            "com.tencent.tmgp.supercell.clashofclans",
            "com.philzhu.www.ddz",
            "com.happyelements.happyfishandroidcns",
            "cn.fangcun.mxm.ucweb",
            "com.tencent.tmgp.qblykilltext",
            "com.qq.ac.android",
            "mt.shadow",
            "com.tophotapp.motohero",
            "com.huawei.browser",
            "com.vivo.browser",
            "com.android.browser",
            "com.mi.globalbrowser",
            "com.mi.browser",
            "com.sec.android.app.sbrowser"
    );

    final static List<String> BlackListApps_start_pkg = Arrays.asList(
            "com.ss.android.ugc.trill",
            "com.google.android.youtube",
            "com.instagram.android",
            "com.tencent.ig",
            "com.facebook.katana"
    );

    final static List<String> BlackListApps_start_name = Arrays.asList(
            "TikTok",
            "YouTube",
            "Instagram",
            "PUBG",
            "Facebook"
    );



}
